name: garbage_cleaner_app
description: A Flutter app for cleaning staff to manage garbage collection.
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  camera: ^0.10.0+1
  geolocator: ^9.0.1
  flutter_map: ^3.0.0
  latlong2: ^0.8.1
  image_picker: ^0.8.5+3
  path_provider: ^2.0.11
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 